name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf462c3736fda8fc59be6d62a038f504801a8899673206cf31bce6d7223afc59"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
