name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f55da5169ce892fca3bcb1f65f8b36996cf83af973daeac4e7e0f5c0f70abc76"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
