name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e085aac711b36213c23439dd8df2ed6d438703efb88374024783a301ae2a82b2"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
