name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a147a82041b92c9c93433cea2fddd6c5b678a0bf519d23268daa96ee9801d87"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
