name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57de246adde7df75a29713e33e90503ebaaeee50a284514cdd32bc2ff46bdfa5"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
