name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132a0fbec8e2af435be243add495113e65aff8d7b3c824efb8f8826a8e6cb453"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
