name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74cec82bb6ebcb9fcfb9287cc4f0c365c6226c9520f9b3538b5f5e933a10dba8"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
