name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "862aa7bfd953841626234341fd0fe728624d9a21650a79f868f37712170d90e4"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
