name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d20e11eaad6d88e73996ee0bceae72363bba0281ab7bb807b9eea1df5bbcc86"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
