name = "Kreog Mods"
author = "emneo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c448d9b1ade6d3fb5055d600e6733ecdfd694e71f63862435782c128c3272e94"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
